Repository Ericsson/codechecker_bazel, pull requests merged in 2025-08, with the labels that each got.

#13 Document all bazel rules provided in the repository
  README.md
Labels: documentation

#28 CI for unit tests
  .github/workflows/test.yml
  test/BUILD
Labels: CI :package:

#53 Create a task issue template
  .github/ISSUE_TEMPLATE/Task.yaml
Labels: enhancement

#49 Create pull request template
  .github/pull_request_template.md
Labels: enhancement

#62 CI refactor
  .github/platform_environment_setup/rhel9/action.yaml
  .github/platform_environment_setup/ubuntu/action.yaml
  .github/workflows/unit_test.yaml
  .github/workflows/unit_test.yml
Labels: CI :package:, non-functional change :peace_symbol:

#60 Move old unit test into a legacy folder
  .github/workflows/unit_test.yaml
  test/test.sh
  test/unit/legacy/BUILD
  test/unit/legacy/__init__.py
  test/unit/legacy/config.json
  test/unit/legacy/inc/inc.h
  test/unit/legacy/src/ctu.cc
  test/unit/legacy/src/fail.cc
  test/unit/legacy/src/lib.cc
  test/unit/legacy/src/pass.cc
  test/unit/legacy/test_legacy.py
Labels: non-functional change :peace_symbol:

#52 Add getting started section
  README.md
Labels: documentation

#68 Fix virtual include test
  test/unit/virtual_include/test_virtual_include.py
Labels: bug, test :ballot_box_with_check:

#59 Unit test: caching
  test/unit/caching/BUILD
  test/unit/caching/__init__.py
  test/unit/caching/linking.h
  test/unit/caching/primary.cc
  test/unit/caching/secondary.cc
  test/unit/caching/test_caching.py
Labels: test :ballot_box_with_check:
